# Generated by Django 3.2 on 2021-06-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_login_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table='Login',
        ),
    ]
